# Numpy
Esta es una libreria de algebra lineal para python, es rapida ya que tiene enlaces a librerias en c.

## Instalacion
Para instalar esta libreria se debe utilizar.

pip install numpy


In [3]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/28/75/3b679b41713bb60e2e8f6e2f87be72c971c9e718b1c17b8f8749240ddca8/numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.2-cp312-cp312-win_amd64.whl (15.5 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## Importando numpy
Luego de instalar la libreria esta debe importarse en el archivo donde se va a utilizar.

import numpy as np

In [4]:
import numpy as np

## Arreglos en Numpy

Los arreglos vienen en dos tipos: vectores y matrices.
Los vectores son matrices de 1-d 
Las matrices son 2-d

### Crear arreglos dede listas de python


In [6]:
mi_lista = [1,2,3]
mi_lista



[1, 2, 3]

In [8]:

np.array(mi_lista)

array([1, 2, 3])

In [9]:
a = np.array(mi_lista)
type(a)

numpy.ndarray

In [10]:
a.dtype

dtype('int32')

In [11]:
 # Una lista de listas
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix) # conversion de una lista de listas a Matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Metodos integrados

### arange
Devuelve valores espaciados uniformemente dentro de un intervalo dado

In [13]:
np.arange(0,10)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
## arange(valor_inicial,valor_final-1,paso)
np.arange(0,11,2) 


array([ 0,  2,  4,  6,  8, 10])

### Zeros y ones
Genera arreglos de ceros o unos

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
# Generar una matriz de ceros de 5 x 5 elementos
np.zeros((5,5)) 


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Devuelve numeros espaciados uniformemente dentro de un intervalo dado.

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
# Generar 50 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Crea una matriz identidad

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numeros aleatorios

#### rand
Crea un arreglo de la forma dada y rellenela con muestras aleatorias

In [21]:
# creacion de un arreglo de 5x5
#Los numeros aleatorios seran de una distribucion uniforme
np.random.rand(5,5)


array([[0.87322169, 0.66690443, 0.61194981, 0.04084213, 0.19102815],
       [0.94506326, 0.90617016, 0.80133789, 0.28070648, 0.96738094],
       [0.36750033, 0.4092935 , 0.00151139, 0.6647091 , 0.40877753],
       [0.2223673 , 0.56875343, 0.26360781, 0.19615379, 0.46873255],
       [0.66692981, 0.24031526, 0.2834191 , 0.15347035, 0.95538683]])

#### randn
Devuelve una muestra de la distribucion "estandar normal"


In [22]:
# creacion de un arreglo de 5x5
#Los numeros aleatorios seran de una distribucion "estándar normal"
np.random.randn(5,5)


array([[ 2.44318811,  2.64124948, -0.30265554, -0.24145895, -0.59995166],
       [-0.63147771, -0.89008345, -0.4091247 ,  0.21618271, -1.41647093],
       [ 0.42613294, -0.00888557, -0.99881223, -0.34366176,  1.63774336],
       [ 0.34470824, -0.64258858, -1.75495797,  0.13182935, -0.60832018],
       [ 0.07651441, -0.16777859,  0.80770338, -0.47632749,  0.11729738]])

#### randint
Entrega numeros aleatorios desde inicio (inclusivo) hasta final (exclusivo) 

In [23]:
# Genera un numero aleatorio entre 1 y 99
np.random.randint(1,100) 


97

In [24]:
# Genera un arreglo de 10 elementos entre 1 y 99
np.random.randint(1,100,(10,2)) 


array([[97, 53],
       [67, 88],
       [20, 88],
       [ 7, 89],
       [52, 38],
       [96, 54],
       [38, 29],
       [29, 16],
       [13, 71],
       [71, 95]])

### Atributos y metodos de los arreglos

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
ranarr


array([29, 13, 49, 48, 19, 22, 27, 38, 41, 48])

#### reshape 
Devuelve una matriz que contiene los mismos datos con una nueva distribucion


In [27]:
# arr es un vector de 25 elementos 
# y se convertira en una matriz de 5x5
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max
Devuelve el valor maximo de la matriz

In [30]:
ranarr

array([29, 13, 49, 48, 19, 22, 27, 38, 41, 48])

In [28]:

ranarr.max() 

49

#### argmax
Devuelve la posicion del valor maximo de la matriz

In [29]:
ranarr.argmax()

2

#### min
Devuelve el valor minimo de la matriz

In [31]:
ranarr.min()

13

#### argmin
Devuelve la posicion del valor minimo de la matriz

In [32]:
ranarr.argmin()

1

#### shape
Es un atributo que los arreglos tienen para definir sus dimensiones

In [33]:
arr.shape

(25,)

In [34]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension horizontal
arr.reshape(1,25)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension vertical
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

#### dtype
Sirve para obtener los tipos de datos dentro del arreglo


In [37]:
arr.dtype

dtype('int32')

#### size
Numero de elementos del arreglo


In [38]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d.size


9

#### ndim
Numero de dimensiones del arreglo 

In [39]:
arr_2d.ndim


2

### Indexacion y seleccion con corchetes
La forma mas sencilla de eligir uno o algunos elementos de una matriz es similar a las listas de python

In [40]:
arr[8]

8

In [41]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
arr[1:5]


array([1, 2, 3, 4])

### Broadcasting (Difusion)
Los arreglos de Numpy difieren de una lista normal de python en su capacidad de broadcasting, que es asignar un valor a un rango de posiciones.

In [42]:
# definiendo un valor para todo un rango de posiciones (Broadcasting)
# Asignar el numero 100 a las pocisiones desde el 0 hasta el 4
arr[0:5]=100 
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [44]:
#NOTA importante en la seleccion de rangos (sclicing)
# los arreglos son mutables
slice_of_arr = arr[0:6]
slice_of_arr


array([100, 100, 100, 100, 100,   5])

In [45]:
#Cambiar todos los valores a 99
slice_of_arr[:]=99
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [48]:
#Creando una matriz de zeros
arr2d = np.zeros((10,10))
arr2d

#Tamaño del arreglo
arr_length = arr2d.shape[1]
arr_length

# Creando una matriz con elementos que contienen el valor correspondiente a la posicion de la fila
for i in range(arr_length):
    arr2d[i] = i
    
arr2d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [49]:
# sacar las filas 2, 4 , 6, 8
arr2d[[2,4,6,8]] # observe el uso de los dobles corchetes


array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

## Operaciones con numpy
Numpy facilita para hacer operaciones elemento a elemento.

In [1]:
# observar el comportamiento de las listas
lista = list(range(10))
lista


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
# Esta operacion concatena las listas
lista + lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# Este procedimiento hace que se repita la lista por el numero de veces
lista * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

con numpy

In [6]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr * 3 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
arr - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [11]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Funciones universales

### sqrt
calcula la raiz cuadrada

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### exp()
calcula el exponencial

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### max()
Obtiene el valor maximo como una funcion

In [14]:
np.max(arr)

9

### sin()
Calcula el seno de cada elemento

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### log()
calcula el logaritmo

In [16]:
np.log(arr)

C:\Users\Jorge HN\AppData\Local\Temp\ipykernel_13004\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### abs()
Calcula el valor absoluto

In [17]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### std()
Calcula la desviacion estandar

In [18]:
np.std(arr)

2.8722813232690143

### mean()
Calcula el promedio

In [19]:
np.mean(arr)

4.5

### median()
Calcula la media

In [20]:
np.median(arr)

4.5

### var()
Calcula la varianza


In [21]:
np.var(arr)

8.25

In [22]:
#creacion de una matriz de ejemplo
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Transpuesta T

In [23]:
# transpuesta de una matriz
arr_2d.T # tambien puede ser arr_2d.transpose()


array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

### Multiplicacion de matrices

In [24]:
# Multiplicacion de matrices
a = np.array([1,4,3]) # vector = arreglo de 1 dimension
b = np.array([2,-1,5]) # vector = arreglo de 1 dimension
a@b


13

### Producto punto

In [25]:
# Multiplicacion de matrices
# Producto Punto
a = np.array(([2,0,1],[3,0,0],[5,1,1]))
b = np.array(([1,0,1],[1,2,1],[1,1,0]))
a@b 


array([[3, 1, 2],
       [3, 0, 3],
       [7, 3, 6]])

In [26]:
#Tambien puede ser de esta forma
np.dot(a,b)


array([[3, 1, 2],
       [3, 0, 3],
       [7, 3, 6]])

### Producto cruz

In [27]:
# Producto Cruz
a = np.array([1,4,3]) # vector = arreglo de 1 dimension
b = np.array([2,-1,5]) # vector = arreglo de 1 dimensi
np.cross(a,b)


array([23,  1, -9])